/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.edu.poli;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testValorAbsoluto() {
    	assertEquals(10, App.valorAbsoluto(10));
    	assertEquals(5, App.valorAbsoluto(-5));
    	assertEquals(7.5f, App.valorAbsoluto(-7.5f));
    }

    @Test
    void testEsPar() {
    	assertTrue(App.esPar(2));
    	assertTrue(App.esPar(-10));
    	assertFalse(App.esPar(13));
    }
}
